package la.gazelle;

import Bd.ChambresBD;
import Bd.ReservationBd;
import com.sun.imageio.plugins.png.RowFilter;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class frame1 extends javax.swing.JFrame {
    
    /**
     * Creates new form frame1
     */
    
    
    Bd.ReservationBd reservationBd = new ReservationBd();
    public frame1() {
        this.setLocation(0,20);
        //initComponents();
        initComponents();
        listed();
        listedSalle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void listed(){
            DefaultTableModel table=new DefaultTableModel();
            table.addColumn("id_res");
            table.addColumn("nom_cl");//from Client
            table.addColumn("prenom_cl");
            table.addColumn("N°Tel");//from Client
            table.addColumn("num_bloc");//from bloc
            table.addColumn("num_ch");//from Chambre
            table.addColumn("Type_ch");
            table.addColumn("date_e");//from Client
            table.addColumn("date_s");//from Client
           
            
            try{
                Connection konn=LaGazelle.connectTODB();
                System.out.println("reservation_Chambres");
                String sql1="SELECT * FROM `reservation_ch`";
                Statement S=konn.createStatement();
                ResultSet R=S.executeQuery(sql1);
                
                while (R.next()) {
                String id_cl=R.getString(2);
                System.out.println("__Clien res Chambres____"+id_cl);
                String sql2="SELECT * FROM  `client` where id_cl="+id_cl;
                Statement u=konn.createStatement();
                ResultSet P=u.executeQuery(sql2);
                
                String num_ch=R.getString(4);
                String sql3="SELECT * FROM  `chambre` where num_ch="+num_ch;
                Statement n=konn.createStatement();
                ResultSet o=n.executeQuery(sql3);
                
              
                while((P.next())&&(o.next()) ){
                     System.err.println("_____________"+P.getString("nom_cl"));
                     System.err.println("_____________"+o.getString("num_ch"));
                     table.addRow(new Object[]{
                     R.getString(1),
                     P.getString("nom_cl"),
                     P.getString("prenom_cl"),
                     P.getString("tel"),
                     o.getString("num_bloc"),
                     o.getString("num_ch"),
                     o.getString("type_ch"),
                     R.getString(5),
                     R.getString(6),
                     
                     });  
                }
                
               }
             res_ch.setModel(table);
             
            }catch(Exception e){
                System.out.println("ma rahch yjib les reservation des chambres");
            }
            
        }
    
    public void listedSalle(){
           DefaultTableModel tableSalles=new DefaultTableModel();
            tableSalles.addColumn("id_res");
            tableSalles.addColumn("nom_cl");//from Client
            tableSalles.addColumn("prenom_cl");
            tableSalles.addColumn("N°Tel");//from Client
             tableSalles.addColumn("Type_salle");
            tableSalles.addColumn("num_salle");//from Chambre
            tableSalles.addColumn("date_e");//from Client
            tableSalles.addColumn("date_s");//from Client
           
            
            try{
                Connection k=LaGazelle.connectTODB();
                System.out.println("reservation_salle");
                String sql7="SELECT * FROM `reservation_salle`";
                Statement S=k.createStatement();
                ResultSet y=S.executeQuery(sql7);
                
                while (y.next()) {
                String id_cl=y.getString("id_cl");
                System.out.println("___Clien res Salle___"+id_cl);
                String sql8="SELECT * FROM  `client` where id_cl="+id_cl;
                Statement u=k.createStatement();
                ResultSet l=u.executeQuery(sql8);
                
                String num_s=y.getString("num_s");
                String sql9="SELECT * FROM  `salle` where num_s="+num_s;
                Statement n=k.createStatement();
                ResultSet w=n.executeQuery(sql9);
                
              
                while((l.next())&&(w.next()) ){
                     System.err.println("_____________"+l.getString("nom_cl"));
                     System.err.println("_____________"+w.getString("num_s"));
                     tableSalles.addRow(new Object[]{
                     y.getString(1),
                     l.getString("nom_cl"),
                     l.getString("prenom_cl"),
                     l.getString("tel"),
                     w.getString("type_s"),
                     w.getString("num_s"),
                     y.getString(4),
                     y.getString(5),
                   
                     });  
                }
                
               }
             res_Salle.setModel(tableSalles);
             
            }catch(Exception e){
                System.out.println("hnaa ma rahch yjib les reservation des salles");
            }
        
        
    }
    
    /*public void shearch (String str){
       DefaultTableModel model =(DefaultTableModel) res_ch.getModel();
       
        TableRowSorter<DefaultTableModel> trs=new TableRowSorter<>(model);
        res_ch.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilte(str));
    }*/
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        Salle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        crs3 = new javax.swing.JPanel();
        Chmbres = new javax.swing.JPanel();
        crs2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Riservation = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        crs1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Client = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        crs4 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        ChambrePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Reservation = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        res_ch = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        res_Salle = new javax.swing.JTable();
        Update = new javax.swing.JLabel();
        addtxt = new javax.swing.JLabel();
        Cl_Nom = new javax.swing.JPanel();
        AddLocationCh = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddLocationSalle = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Shersh_res = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nom_prenom = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        Salle.setBackground(new java.awt.Color(51, 0, 102));
        Salle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalleMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("salle ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/vip-room.png"))); // NOI18N

        crs3.setBackground(new java.awt.Color(51, 0, 102));

        javax.swing.GroupLayout crs3Layout = new javax.swing.GroupLayout(crs3);
        crs3.setLayout(crs3Layout);
        crs3Layout.setHorizontalGroup(
            crs3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        crs3Layout.setVerticalGroup(
            crs3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SalleLayout = new javax.swing.GroupLayout(Salle);
        Salle.setLayout(SalleLayout);
        SalleLayout.setHorizontalGroup(
            SalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalleLayout.createSequentialGroup()
                .addComponent(crs3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SalleLayout.setVerticalGroup(
            SalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalleLayout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(SalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15))
            .addComponent(crs3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Chmbres.setBackground(new java.awt.Color(51, 0, 102));
        Chmbres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChmbresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChmbresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChmbresMouseExited(evt);
            }
        });

        crs2.setBackground(new java.awt.Color(51, 0, 102));

        javax.swing.GroupLayout crs2Layout = new javax.swing.GroupLayout(crs2);
        crs2.setLayout(crs2Layout);
        crs2Layout.setHorizontalGroup(
            crs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        crs2Layout.setVerticalGroup(
            crs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Chambres");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hotel.png"))); // NOI18N

        javax.swing.GroupLayout ChmbresLayout = new javax.swing.GroupLayout(Chmbres);
        Chmbres.setLayout(ChmbresLayout);
        ChmbresLayout.setHorizontalGroup(
            ChmbresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChmbresLayout.createSequentialGroup()
                .addComponent(crs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(57, 57, 57))
        );
        ChmbresLayout.setVerticalGroup(
            ChmbresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChmbresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChmbresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(crs2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Riservation.setBackground(new java.awt.Color(51, 0, 102));
        Riservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RiservationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RiservationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RiservationMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Réservation");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bookingg.png"))); // NOI18N

        crs1.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout crs1Layout = new javax.swing.GroupLayout(crs1);
        crs1.setLayout(crs1Layout);
        crs1Layout.setHorizontalGroup(
            crs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        crs1Layout.setVerticalGroup(
            crs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RiservationLayout = new javax.swing.GroupLayout(Riservation);
        Riservation.setLayout(RiservationLayout);
        RiservationLayout.setHorizontalGroup(
            RiservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RiservationLayout.createSequentialGroup()
                .addComponent(crs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(48, 48, 48))
        );
        RiservationLayout.setVerticalGroup(
            RiservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RiservationLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(RiservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RiservationLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(RiservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RiservationLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RiservationLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addComponent(crs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel14.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("La Gazelle");

        Client.setBackground(new java.awt.Color(51, 0, 102));
        Client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClientMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Client");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/kyc.png"))); // NOI18N

        crs4.setBackground(new java.awt.Color(51, 0, 102));

        javax.swing.GroupLayout crs4Layout = new javax.swing.GroupLayout(crs4);
        crs4.setLayout(crs4Layout);
        crs4Layout.setHorizontalGroup(
            crs4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        crs4Layout.setVerticalGroup(
            crs4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ClientLayout = new javax.swing.GroupLayout(Client);
        Client.setLayout(ClientLayout);
        ClientLayout.setHorizontalGroup(
            ClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientLayout.createSequentialGroup()
                .addComponent(crs4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(77, 77, 77))
        );
        ClientLayout.setVerticalGroup(
            ClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(22, 22, 22))
            .addGroup(ClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(crs4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gazell.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Chmbres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Salle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Riservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(Riservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Chmbres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Salle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ChambrePanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Reservation.setFocusCycleRoot(true);
        Reservation.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        res_ch.setFont(new java.awt.Font("Tekton Pro Ext", 0, 11)); // NOI18N
        res_ch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, "", null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Reservation", "Nom Client", "prenom Client", "N° Tel", "bloc", "num_Chambre", "Type_Chambre", "Date Entrer", "Date Sortie", "Total (DA)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        res_ch.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        res_ch.setGridColor(new java.awt.Color(255, 255, 255));
        res_ch.setName(""); // NOI18N
        res_ch.setRowHeight(20);
        res_ch.setRowMargin(10);
        jScrollPane2.setViewportView(res_ch);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        Reservation.addTab("Chambres Reserver", jPanel5);

        res_Salle.setFont(new java.awt.Font("Tekton Pro Ext", 0, 11)); // NOI18N
        res_Salle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_resrvation", "Nom Client", "Prenom Client", "Num_cl", "Type_Salle", "Num_salle", "Date Dubet", "Date_fein", "Montant a paier(DA)"
            }
        ));
        res_Salle.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(res_Salle);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        Reservation.addTab("Salles Reserver", jPanel6);

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/updated.png"))); // NOI18N
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });

        addtxt.setForeground(new java.awt.Color(0, 153, 51));
        addtxt.setText("Refrichire");

        javax.swing.GroupLayout ChambrePanelLayout = new javax.swing.GroupLayout(ChambrePanel);
        ChambrePanel.setLayout(ChambrePanelLayout);
        ChambrePanelLayout.setHorizontalGroup(
            ChambrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChambrePanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ChambrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addtxt)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(ChambrePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reservation, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ChambrePanelLayout.setVerticalGroup(
            ChambrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChambrePanelLayout.createSequentialGroup()
                .addGroup(ChambrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChambrePanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ChambrePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addtxt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reservation, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Reservation.getAccessibleContext().setAccessibleName("Salle Reserver");

        Cl_Nom.setBackground(new java.awt.Color(153, 0, 255));
        Cl_Nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cl_NomKeyTyped(evt);
            }
        });

        AddLocationCh.setBackground(new java.awt.Color(153, 0, 255));
        AddLocationCh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLocationChMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddLocationChMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddLocationChMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Reserver une Chambre");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/beds.png"))); // NOI18N

        javax.swing.GroupLayout AddLocationChLayout = new javax.swing.GroupLayout(AddLocationCh);
        AddLocationCh.setLayout(AddLocationChLayout);
        AddLocationChLayout.setHorizontalGroup(
            AddLocationChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLocationChLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(27, 27, 27))
        );
        AddLocationChLayout.setVerticalGroup(
            AddLocationChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLocationChLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddLocationChLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(21, 21, 21))
        );

        AddLocationSalle.setBackground(new java.awt.Color(153, 0, 255));
        AddLocationSalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLocationSalleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddLocationSalleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddLocationSalleMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Reserver une Salle");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/vip-room.png"))); // NOI18N

        javax.swing.GroupLayout AddLocationSalleLayout = new javax.swing.GroupLayout(AddLocationSalle);
        AddLocationSalle.setLayout(AddLocationSalleLayout);
        AddLocationSalleLayout.setHorizontalGroup(
            AddLocationSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLocationSalleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(27, 27, 27))
        );
        AddLocationSalleLayout.setVerticalGroup(
            AddLocationSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLocationSalleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddLocationSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 0, 255));
        jTextField1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Reservation");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/information-desk.png"))); // NOI18N

        Shersh_res.setBackground(new java.awt.Color(153, 0, 255));
        Shersh_res.setBorder(null);
        Shersh_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Shersh_resActionPerformed(evt);
            }
        });
        Shersh_res.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Shersh_resKeyReleased(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));

        nom_prenom.setBackground(new java.awt.Color(153, 0, 255));
        nom_prenom.setFont(new java.awt.Font("Tekton Pro Ext", 0, 12)); // NOI18N
        nom_prenom.setForeground(new java.awt.Color(255, 255, 255));
        nom_prenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom_prenom.setText("Entrer le Nom de Client");
        nom_prenom.setBorder(null);
        nom_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_prenomActionPerformed(evt);
            }
        });
        nom_prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nom_prenomKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout Cl_NomLayout = new javax.swing.GroupLayout(Cl_Nom);
        Cl_Nom.setLayout(Cl_NomLayout);
        Cl_NomLayout.setHorizontalGroup(
            Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cl_NomLayout.createSequentialGroup()
                .addGroup(Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cl_NomLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(Cl_NomLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cl_NomLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cl_NomLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(537, 537, 537))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cl_NomLayout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(816, 816, 816))))
                    .addGroup(Cl_NomLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(AddLocationCh, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(AddLocationSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(Cl_NomLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Shersh_res, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nom_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(816, 816, 816))
            .addGroup(Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cl_NomLayout.createSequentialGroup()
                    .addGap(448, 448, 448)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1030, Short.MAX_VALUE)))
        );
        Cl_NomLayout.setVerticalGroup(
            Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cl_NomLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cl_NomLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddLocationCh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddLocationSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cl_NomLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Shersh_res, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Cl_NomLayout.createSequentialGroup()
                                .addGroup(Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nom_prenom))
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(Cl_NomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cl_NomLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(120, Short.MAX_VALUE)))
        );

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/closing.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/008.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/notif.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1004, 1004, 1004)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ChambrePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cl_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cl_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ChambrePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SetColr(JPanel panel){
        panel.setBackground(new Color(135,112,225));
    }
    
    private void ResetColr(JPanel panel){
        
        panel.setBackground(Color.decode("#330066"));
    }
    
    private void AddLocationChMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLocationChMouseEntered
        SetColr( AddLocationCh);
    }//GEN-LAST:event_AddLocationChMouseEntered

    private void AddLocationChMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLocationChMouseExited
        AddLocationCh.setBackground(Color.decode("#9900ff"));   
    }//GEN-LAST:event_AddLocationChMouseExited

    private void AddLocationSalleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLocationSalleMouseEntered
        SetColr(AddLocationSalle);
    }//GEN-LAST:event_AddLocationSalleMouseEntered

    private void AddLocationSalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLocationSalleMouseExited
        AddLocationSalle.setBackground(Color.decode("#9900ff"));    }//GEN-LAST:event_AddLocationSalleMouseExited

    private void ChmbresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChmbresMouseClicked
        crs2.setBackground(Color.decode("#ffcc00"));
        crs1.setBackground(Color.decode("#330066"));
        crs3.setBackground(Color.decode("#330066"));
        crs4.setBackground(Color.decode("#330066"));
        RoomsPanel Rooms=new RoomsPanel();
        Rooms.setVisible(true);
        
    }//GEN-LAST:event_ChmbresMouseClicked

    
  
    private void ChmbresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChmbresMouseEntered
        SetColr(Chmbres);
    }//GEN-LAST:event_ChmbresMouseEntered

    private void ChmbresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChmbresMouseExited
        ResetColr(Chmbres);
        //Riservation.setBackground(Color.decode("#330066"));
    }//GEN-LAST:event_ChmbresMouseExited

    private void SalleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalleMouseEntered
        SetColr(Salle);
    }//GEN-LAST:event_SalleMouseEntered

    private void SalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalleMouseExited
        ResetColr(Salle);
    }//GEN-LAST:event_SalleMouseExited

    private void SalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalleMouseClicked
        //crsor colers
        crs3.setBackground(Color.decode("#ffcc00"));
        crs1.setBackground(Color.decode("#330066"));
        crs2.setBackground(Color.decode("#330066"));
        crs4.setBackground(Color.decode("#330066"));
        SallePanel Salle=new SallePanel();
        Salle.setVisible(true);
    }//GEN-LAST:event_SalleMouseClicked

    private void ClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientMouseClicked
        //crsor colers
        crs4.setBackground(Color.decode("#ffcc00"));
        crs1.setBackground(Color.decode("#330066"));
        crs3.setBackground(Color.decode("#330066"));
        crs1.setBackground(Color.decode("#330066"));
        ClientPanel Client=new ClientPanel();
        Client.setVisible(true);
        
    }//GEN-LAST:event_ClientMouseClicked

    private void ClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientMouseEntered
        Client.setBackground(Color.decode("#7641ab"));
    }//GEN-LAST:event_ClientMouseEntered

    private void ClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientMouseExited
        ResetColr(Client);
    }//GEN-LAST:event_ClientMouseExited

    private void RiservationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiservationMouseEntered
        SetColr(Riservation);
    }//GEN-LAST:event_RiservationMouseEntered

    private void RiservationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiservationMouseExited
        ResetColr(Riservation);
    }//GEN-LAST:event_RiservationMouseExited

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void AddLocationChMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLocationChMouseClicked
        // TODO add your handling code here:
        Reservation_des_Chambres res_ch=new Reservation_des_Chambres();
        res_ch.setVisible(true);
    }//GEN-LAST:event_AddLocationChMouseClicked

    private void RiservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiservationMouseClicked
        crs1.setBackground(Color.decode("#ffcc00"));
        crs2.setBackground(Color.decode("#330066"));
        crs3.setBackground(Color.decode("#330066"));
        crs4.setBackground(Color.decode("#330066"));
        
    }//GEN-LAST:event_RiservationMouseClicked

    private void AddLocationSalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLocationSalleMouseClicked
      Reservation_des_Salle reservation_des_Salle=new Reservation_des_Salle();
      reservation_des_Salle.setVisible(true);
    }//GEN-LAST:event_AddLocationSalleMouseClicked

    private void Shersh_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Shersh_resActionPerformed

        // TODO add your handling code here:    
    }//GEN-LAST:event_Shersh_resActionPerformed

    private void Shersh_resKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Shersh_resKeyReleased
       String serchTxt= Shersh_res.getText();
    }//GEN-LAST:event_Shersh_resKeyReleased

    private void Cl_NomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cl_NomKeyTyped
       
    }//GEN-LAST:event_Cl_NomKeyTyped

    private void nom_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_prenomActionPerformed
       
    }//GEN-LAST:event_nom_prenomActionPerformed

    private void nom_prenomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_prenomKeyPressed
          if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
           String Nom_cl = nom_prenom.getText();
           
          if(Nom_cl!=null){
           
           if(!Nom_cl.contains(" ")){
              JOptionPane.showMessageDialog(null, "no users found, try adding a new user");
            }else{
             
              String [] Nom_prenom=Nom_cl.split(" ");
              String Nom=Nom_prenom[0];
              String Prenom=Nom_prenom[1];
              
              System.out.println("Nom.>> " + Nom+"  Prenom.>>"+Prenom);
              ResultSet userDB = reservationBd.searchAnUser(Nom,Prenom);
               
            try{
            while(userDB.next()){
            String id=userDB.getString("id_cl");
            System.out.println("___idClientforSherchAllReservation__"+id);
            ResultSet AllResOfCl = reservationBd.serchAllReservationCl(id);
            
            DefaultTableModel table=new DefaultTableModel();
            table.addColumn("id_res");
            table.addColumn("nom_cl");//from Client
            table.addColumn("prenom_cl");
            table.addColumn("N°Tel");//from Client
            table.addColumn("num_bloc");//from bloc
            table.addColumn("num_ch");//from Chambre
            table.addColumn("Type_ch");
            table.addColumn("date_e");//from Client
            table.addColumn("date_s");//from Client
            table.addColumn("prix_joure");//from Chambre
            
            while (AllResOfCl.next()) {
                    /* System.err.println("_____________"+AllResOfCl.getString("nom_cl"));
                     System.err.println("_____________"+o.getString("num_ch"));*/
                     table.addRow(new Object[]{
                     AllResOfCl.getString("id_res"),
                     userDB.getString("nom_cl"),
                     userDB.getString("prenom_cl"),
                     userDB.getString("tel"),
                    /* o.getString("num_bloc"),
                     o.getString("num_ch"),
                     o.getString("type_ch"),*/
                     AllResOfCl.getString(4),
                     AllResOfCl.getString(5),
                 });  
                     
                }
                     res_ch.setModel(table); 
            }

          } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "err from displaying to board");
        }
            
         }
         
         }
     }else listed();
    }//GEN-LAST:event_nom_prenomKeyPressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
   
    }//GEN-LAST:event_jLabel9MouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        listed();
        listedSalle();
    }//GEN-LAST:event_UpdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddLocationCh;
    private javax.swing.JPanel AddLocationSalle;
    private javax.swing.JPanel ChambrePanel;
    private javax.swing.JPanel Chmbres;
    private javax.swing.JPanel Cl_Nom;
    private javax.swing.JPanel Client;
    private javax.swing.JTabbedPane Reservation;
    private javax.swing.JPanel Riservation;
    private javax.swing.JPanel Salle;
    private javax.swing.JTextField Shersh_res;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel addtxt;
    private javax.swing.JPanel crs1;
    private javax.swing.JPanel crs2;
    private javax.swing.JPanel crs3;
    private javax.swing.JPanel crs4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nom_prenom;
    private javax.swing.JTable res_Salle;
    private javax.swing.JTable res_ch;
    // End of variables declaration//GEN-END:variables
}
