package la.gazelle;

import Bd.ChambresBD;
import Bd.SallesBD;
import Classes.Chambre;
import Classes.Salle;
import com.sun.java.swing.plaf.windows.resources.windows;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class SallePanel extends javax.swing.JFrame {

    /**
     * Creates new form SallePanel
     */
    
    
   Classes.Salle salle = new Salle();
   ArrayList<String> salletyps = new ArrayList<>();
    ResultSet result;
    Bd.SallesBD Salledb = new SallesBD();
    
    
    
    public SallePanel() {
        this.setLocation(250,150);
       
        initComponents();
        
        listed();
        
        salletyps.add("salle des fêtes");
        salletyps.add(" salle des Congrès");
        salletyps.add("Auditorium");
        
    }
    
    public void listed(){
            DefaultTableModel table=new DefaultTableModel();
            
            table.addColumn("num_s");
            table.addColumn("type_s");
            table.addColumn("disponibilité");
            table.addColumn("prix");
           
            try{
             Connection konn=LaGazelle.connectTODB();
             String sql="SELECT * FROM `salle`";
             Statement S=konn.createStatement();
             ResultSet R=S.executeQuery(sql);
             
             while(R.next()){
                 table.addRow(new Object[]{
                     R.getString(1),
                     R.getString(2),
                     R.getString(3),
                     R.getString(4),
                 });
             }SalleTab.setModel(table);
            }catch(Exception e){
                System.out.println("hnaa");
            }
            
        }
    
    private void populateSalleTable()
    {
        result = Salledb.getSalles();
        SalleTab.setModel(DbUtils.resultSetToTableModel(result));
        Salledb.flushAll();
      
    }
     private void salleObjectCreation()
    {
        // **************************************get information from the panel *********************
        salle = new Salle();
        salle.setNum_s(num_s.getText());
        salle.setType_s(salleType.getSelectedItem().toString());
        salle.setPrix_s(Integer.parseInt(prix_s.getText()));
      
    }

     //resste filds
    private void clearSallePanel()
    {
        salle = new Salle();
        SalleTab.clearSelection();
        num_s.setText("");
        salleType.setSelectedIndex(0);
        prix_s.setText("");
       
    }
    
    
    //return ComboSelected
     private int getComboSearchIndex(String item)
      {
          for( int i=1;i<salletyps.size() ; i++)
          {
              if(item.equals(salletyps.get(i)))
              {
                  return i;
              }
          }
          return 0;
      }
     
      private void displayTosalleTextField(int row)
    {
       // for(int i=0; combo_roomType.)
        num_s.setText(SalleTab.getModel().getValueAt(row, 0)+"");
        int indxType = getComboSearchIndex(SalleTab.getModel().getValueAt(row, 1)+"");  
        salleType.setSelectedIndex(indxType);
        prix_s.setText(SalleTab.getModel().getValueAt(row, 3)+"");
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SalleTab = new javax.swing.JTable();
        salleType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Edit_reservation2 = new javax.swing.JLabel();
        Edit_reservation = new javax.swing.JLabel();
        Edit_reservation1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        num_s = new javax.swing.JTextField();
        addSalle = new javax.swing.JLabel();
        Edite = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        deletxt = new javax.swing.JLabel();
        edittxt = new javax.swing.JLabel();
        addtxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prix_s = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Nos Salle");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/vip-room.png"))); // NOI18N

        SalleTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "num_Salle", "type", "disponibilité", "prix"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SalleTab.setGridColor(new java.awt.Color(255, 255, 255));
        SalleTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalleTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SalleTab);

        salleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "salle des fêtes", "salle des Congrès", "Auditorium" }));
        salleType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salleTypeActionPerformed(evt);
            }
        });

        jLabel2.setText("Type Salle");

        jLabel3.setText("N° Salle");

        addSalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/updated.png"))); // NOI18N
        addSalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSalleMouseClicked(evt);
            }
        });

        Edite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });

        deletxt.setForeground(new java.awt.Color(255, 0, 0));
        deletxt.setText("Supprimer");

        edittxt.setForeground(new java.awt.Color(0, 102, 255));
        edittxt.setText("Modifier");

        addtxt.setForeground(new java.awt.Color(0, 153, 51));
        addtxt.setText("Ajouert");

        jLabel5.setText("prix");

        prix_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prix_sActionPerformed(evt);
            }
        });

        jLabel9.setText("DA");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sginout.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(num_s, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prix_s, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addtxt)
                                .addGap(23, 23, 23)
                                .addComponent(edittxt)
                                .addGap(18, 18, 18)
                                .addComponent(deletxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(Edite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Edit_reservation1)
                        .addGap(0, 0, 0)
                        .addComponent(Edit_reservation)
                        .addGap(0, 0, 0)
                        .addComponent(Edit_reservation2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Edit_reservation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Edit_reservation1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Edit_reservation2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(salleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(num_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(prix_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Edite, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addtxt)
                            .addComponent(edittxt)
                            .addComponent(deletxt))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salleTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salleTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salleTypeActionPerformed

    private void prix_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prix_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prix_sActionPerformed

    private void SalleTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalleTabMouseClicked
        // TODO add your handling code here:
         salle = new Salle();
        Edite.setEnabled(true);
        Delete.setEnabled(true);deletxt.setEnabled(true);
        addSalle.setEnabled(false);addtxt.setEnabled(false);
        int row = SalleTab.getSelectedRow();
        displayTosalleTextField(row);
    }//GEN-LAST:event_SalleTabMouseClicked

    private void addSalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSalleMouseClicked
        // TODO add your handling code here:
        
       salleObjectCreation();
       Salledb.insertSalle(salle);
       populateSalleTable();
       clearSallePanel();
       System.out.println("prblm f l'ajoute");
    }//GEN-LAST:event_addSalleMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        DefaultTableModel model=(DefaultTableModel)SalleTab.getModel();
        try{
            //deleting row from table "View" 
            int index=SalleTab.getSelectedRow();
            model.removeRow(index);
            //delet the row from DB
            int value=Integer.parseInt(model.getValueAt(index,0).toString());
            Salledb.deleteSalle(value);
           
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex+ "\n" + "sélectionner une ligne s'il vous plait");
        }
    }//GEN-LAST:event_DeleteMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        Edite.setEnabled(true);edittxt.setEnabled(true);
        Delete.setEnabled(true);deletxt.setEnabled(true);
        addSalle.setEnabled(true);addtxt.setEnabled(true);
    }//GEN-LAST:event_formMouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
                setVisible(false); 
        dispose(); 

    }//GEN-LAST:event_jLabel22MouseClicked

    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SallePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SallePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SallePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SallePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SallePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Edit_reservation;
    private javax.swing.JLabel Edit_reservation1;
    private javax.swing.JLabel Edit_reservation2;
    private javax.swing.JLabel Edite;
    private javax.swing.JTable SalleTab;
    private javax.swing.JLabel addSalle;
    private javax.swing.JLabel addtxt;
    private javax.swing.JLabel deletxt;
    private javax.swing.JLabel edittxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField num_s;
    private javax.swing.JTextField prix_s;
    private javax.swing.JComboBox<String> salleType;
    // End of variables declaration//GEN-END:variables
}
